### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by evangeloper** [manusa/actions-publish-docker#4]
Curiosity killed the cat xD

**Comment by manusa** [comment]
Hi Mr. Schrödinger,

This is a custom [GitHub action](https://github.com/features/actions) to build and publish to a registry (e.g. https://hub.docker.com) Docker images.

It's still under development and will probably be ready by the end of week.

I'm currently testing it's integration in https://github.com/manusa/mnIMAPSync. More specifically the boundaries of the action's [expression syntax](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions) to see if more features will be needed (you can check the progress here: https://github.com/manusa/mnIMAPSync/blob/feature/%2330-dockerize/.github/workflows/build.yml#L26).

Any inputs are welcome ;)

**Comment by evangeloper** [comment]
Hello Mr. Manusa,

Thank you for the introduction.

Nice, I will keep an eye on it.

In your repos, are you building more stuff besides the Docker image, or it's just a step in your build process?

**Comment by manusa** [comment]
It's usually one of the latest steps on the build pipeline, and should only be triggered when pushing a Git tag (release version) or push to master (a.k.a. latest) when every previous step completed successfully .

I usually include the following steps in most of my projects (build, test, quality + quality gate, release->Docker, finally depending on the project deploy).

![image](https://user-images.githubusercontent.com/488391/64586258-1445fa00-d39c-11e9-8827-ff16434c9d5a.png)

**Comment by evangeloper** [comment]
So effectivelly you are replacing your current CI/CD pipeline with GitHub actions then?

**Comment by evangeloper** [comment]
Look into Azure Pipelines as well.

**Comment by manusa** [comment]
> So effectivelly you are replacing your current CI/CD pipeline with GitHub actions then?

For all new projects I'm probably going to use GitHub actions/workflows, I find them much more modular than other solutions I've tried and I feel very comfortable creating new actions as they can be implemented using any technology and be easily implemented.

Only feature I miss so far is a global dashboard for all my projects, so I probably end up building one myself.

> Look into Azure Pipelines as well.
I sure will

**Comment by evangeloper** [comment]
"so I probably end up building one myself"
I wouldn't expect any less from you :-)

**Comment by evangeloper** [comment]
The only problem would be vendor lock in, right?
